### ISSUE TITLE
Animation model is separate from normal Character model, leading to having 4 arms

### ISSUE THREAD

**Issue by Ptnecni** [chriscavalluzzi/SuperPioneer#27]
The animation uses an all-black pioneer model on top of your character instead of simply animating your character. This leads to having 4 arms, weird jumping animations and a bunch of Z-fighting.

**Comment by chriscavalluzzi** [comment]
Hey! Does this happen when you're playing offline single-player, multiplayer, or on a dedicated server? And if multiplayer, are you the host?

**Comment by Ptnecni** [comment]
happens with custom animations, unsure if it's only in SP or in MP too
